[build]
  publish = "."

[[headers]]
  for = "/service-worker.js"
  [headers.values]
  Cache-Control = "no-cache"

[[headers]]
  for = "/data/search-index.json"
  [headers.values]
  Cache-Control = "no-cache"
